module.exports = [
  'https://broad-shibboleth-prod.appspot.com',
  'https://all-of-us-workbench-test.appspot.com',
  'https://all-of-us-rw-staging.appspot.com',
  'https://all-of-us-rw-stable.appspot.com',
  'https://all-of-us-rw-perf.appspot.com',
  'https://all-of-us-rw-preprod.appspot.com',
  'https://workbench.researchallofus.org',
  'https://app.terra.bio',
  'https://firecloud.terra.bio',
  'https://datastage.terra.bio',
  'https://anvil.terra.bio',
  'https://ukbiobank.terra.bio',
  'https://baseline.terra.bio',
  'https://terra.biodatacatalyst.nhlbi.nih.gov',
  'https://duos.broadinstitute.org',
  'https://duos.dsp-duos-staging.broadinstitute.org',
  'https://duos.dsp-duos-dev.broadinstitute.org'
]
